services:
  postgres:
    image: mirror.gcr.io/postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trapezial_dev
    ports:
      - 5432:5432
